#!/usr/bin/env node
// Pain Ledger verifier. Copyright (C) 2026 Florin
// SPDX-License-Identifier: GPL-3.0-or-later
// painledger-verify: checks a PainLedger SavedVariables file outside the game.
//
//   node painledger-verify.mjs "path\to\WTF\...\SavedVariables\PainLedger.lua"
//
// It does not run any Lua and does not trust anything the addon computed:
//   1. recomputes the genesis hash from character, realm and start time
//   2. recomputes every log entry's SHA-256 and checks the chain links to the head
//   3. replays every fate draw from its recorded inputs and rebuilds the pool
//      the card was picked from
//   4. prints the run's record: violations, unaccounted time, overrides, rolls
// Exit code 0 = everything checks out, 1 = a problem was found.

import { readFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";

const SEP = "\x1f";
const sha256 = (s) => createHash("sha256").update(Buffer.from(s, "utf8")).digest("hex");
const int = (x) => String(Math.floor(Number(x ?? 0)));

// ---------------------------------------------------------------------------
// Minimal parser for WoW SavedVariables (a Lua table literal per global).
// The source is read as latin1: one character per byte.
// ---------------------------------------------------------------------------
function parseSavedVariables(src) {
  let i = 0;
  const ws = () => {
    for (;;) {
      while (i < src.length && /\s/.test(src[i])) i++;
      if (src.startsWith("--", i)) {
        while (i < src.length && src[i] !== "\n") i++;
      } else return;
    }
  };
  const err = (m) => { throw new Error(`${m} at offset ${i}`); };
  const str = () => {
    const q = src[i++];
    let out = [];
    while (i < src.length && src[i] !== q) {
      let c = src[i++];
      if (c === "\\") {
        const n = src[i++];
        if (n === "n") out.push(10);
        else if (n === "t") out.push(9);
        else if (n === "r") out.push(13);
        else if (n === "\n") out.push(10);
        else if (/[0-9]/.test(n)) {
          let d = n;
          while (d.length < 3 && /[0-9]/.test(src[i])) d += src[i++];
          out.push(Number(d));
        } else out.push(n.charCodeAt(0));
      } else out.push(c.charCodeAt(0));
    }
    i++;
    return Buffer.from(out).toString("utf8");
  };
  const num = () => {
    const m = /^-?(?:0x[0-9a-fA-F]+|\d+\.?\d*(?:[eE][+-]?\d+)?|\.\d+)/.exec(src.slice(i, i + 64));
    if (!m) err("bad number");
    i += m[0].length;
    return Number(m[0]);
  };
  const value = () => {
    ws();
    const c = src[i];
    if (c === "{") return table();
    if (c === '"' || c === "'") return str();
    if (src.startsWith("true", i)) { i += 4; return true; }
    if (src.startsWith("false", i)) { i += 5; return false; }
    if (src.startsWith("nil", i)) { i += 3; return null; }
    return num();
  };
  const table = () => {
    i++; // {
    const entries = [];
    let nextIndex = 1;
    for (;;) {
      ws();
      if (src[i] === "}") { i++; break; }
      let key;
      if (src[i] === "[") {
        i++; key = value(); ws();
        if (src[i] !== "]") err("expected ]");
        i++; ws();
        if (src[i] !== "=") err("expected =");
        i++;
      } else {
        key = nextIndex++;
      }
      entries.push([key, value()]);
      ws();
      if (src[i] === "," || src[i] === ";") i++;
    }
    const isArray = entries.length > 0 && entries.every(([k], idx) => k === idx + 1);
    if (isArray) return entries.map(([, v]) => v);
    const obj = {};
    for (const [k, v] of entries) obj[k] = v;
    return obj;
  };
  const globals = {};
  for (;;) {
    ws();
    if (i >= src.length) break;
    const m = /^[A-Za-z_][A-Za-z0-9_]*/.exec(src.slice(i, i + 200));
    if (!m) err("expected a global name");
    i += m[0].length; ws();
    if (src[i] !== "=") err("expected =");
    i++;
    globals[m[0]] = value();
  }
  return globals;
}

// ---------------------------------------------------------------------------
// Fate tables. Slots are fixed; class cards come from painledger-data.json,
// generated by build_data.py from the same client data as the addon's Data.lua.
// ---------------------------------------------------------------------------
const FATE_SLOTS = {
  1: "Head", 2: "Neck", 3: "Shoulders", 5: "Chest", 6: "Waist", 7: "Legs", 8: "Feet", 9: "Wrists",
  10: "Hands", 11: "Ring 1", 12: "Ring 2", 13: "Trinket 1", 14: "Trinket 2", 15: "Back",
  16: "Main Hand", 17: "Off Hand", 18: "Ranged",
};
const DATA_PATH = fileURLToPath(new URL("./painledger-data.json", import.meta.url));
const DATA = existsSync(DATA_PATH) ? JSON.parse(readFileSync(DATA_PATH, "utf8")) : null;

function pick(parts, n) {
  const hx = sha256(parts.join(SEP));
  return { pick: (parseInt(hx.slice(0, 8), 16) % n) + 1, hash: hx };
}

// ---------------------------------------------------------------------------
function main() {
  const path = process.argv[2];
  if (!path) {
    console.log('Usage: node painledger-verify.mjs "path\\to\\SavedVariables\\PainLedger.lua"');
    process.exit(2);
  }
  // Read as latin1 so every byte is one character; strings are turned back into
  // UTF-8 when parsed, so item names in any client language hash correctly.
  let db;
  try {
    db = parseSavedVariables(readFileSync(path, "latin1").replace(/^\xEF\xBB\xBF/, ""));
    db = db.PainLedgerDB ?? db.RareLedgerDB; // files from before the rename use RareLedgerDB
  } catch {
    db = null;
  }
  if (!db) { console.log("This is not a Pain Ledger SavedVariables file. The right one is\n  WTF\\Account\\<account>\\<realm>\\<character>\\SavedVariables\\PainLedger.lua\n(not the addon file of the same name under Interface\\AddOns)."); process.exit(1); }

  let problems = 0;
  const bad = (m) => { problems++; console.log("  FAIL  " + m); };
  const good = (m) => console.log("  ok    " + m);

  const C = db.chain;
  const log = db.log ?? [];
  console.log(`\nPain Ledger verification: ${C?.name ?? "?"}-${C?.realm ?? "?"}` +
    (C?.class ? ` (${C.race ?? "?"} ${C.class})` : "") + `, ${log.length} log entries` +
    (DATA ? `, data ${DATA.version}` : ""));

  // 1. genesis
  console.log("\nChain");
  if (!C) { bad("no chain in this file (older than 0.10?)"); process.exit(1); }
  const genesis = sha256(["RareLedger", "chain1", C.name, C.realm, int(C.started)].join(SEP));
  genesis === C.genesis ? good(`genesis ${C.genesis.slice(0, 16)} matches ${C.name}-${C.realm}, started ${int(C.started)}`)
    : bad(`genesis does not match: expected ${genesis.slice(0, 16)}, file says ${String(C.genesis).slice(0, 16)}`);

  // 2. entries
  let prev = C.genesis;
  let firstBad = null;
  const bySeq = [];
  log.forEach((e, idx) => {
    if (firstBad) return;
    const seq = idx + 1;
    const body = [int(e.seq), int(e.t), e.st != null ? int(e.st) : "", e.kind ?? "", int(e.amount), int(e.legal),
      e.zone != null ? int(e.zone) : "", e.lvl != null ? int(e.lvl) : "", e.note ?? "", prev].join(SEP);
    if (e.seq !== seq) firstBad = `entry ${seq} has seq ${e.seq}`;
    else if (sha256(body) !== e.h) firstBad = `entry ${seq} (${e.kind}) does not match its hash`;
    else { prev = e.h; bySeq[seq] = e; }
  });
  if (firstBad) bad(firstBad);
  else {
    good(`all ${log.length} entries recomputed, every link intact`);
    prev === C.head && log.length === C.seq ? good(`head ${C.head.slice(0, 16)} is the last entry (#${C.seq})`)
      : bad(`chain head/seq in the file (${String(C.head).slice(0, 16)}, #${C.seq}) do not match the log`);
  }

  // 3. fate draws
  console.log("\nFate draws");
  const hist = db.fate?.history ?? [];
  const cls = (C.class ?? "WARRIOR").toUpperCase(); // files from before 0.11 are the warrior dry run
  if (!DATA) bad("painledger-data.json is missing: put it next to this script");
  if (DATA && C.data && C.data !== DATA.version)
    bad(`this run was recorded with data version ${C.data}, this verifier has ${DATA.version}: pools may differ`);
  const raceBit = DATA?.raceBit?.[C.race];
  const abil = (DATA?.classes?.[cls] ?? []).filter((c) => !c.race || !raceBit || (c.race & raceBit));
  if (DATA && !abil.length) bad(`no cards for class ${cls}`);
  const openSlots = new Set(), openAbil = new Set();
  const slotByName = Object.fromEntries(Object.entries(FATE_SLOTS).map(([k, v]) => [v, Number(k)]));
  const cardOf = (h) => abil.find((c) => (h.card != null ? c.id === h.card : c.label === h.name || c.name === h.name));
  hist.forEach((h, idx) => {
    const n = idx + 1;
    // rebuild the pool exactly as the addon does: locked slots by slot number, then
    // locked abilities in table order that the level allows
    const pool = []; // { label, name, id } in the addon's order
    for (const s of Object.keys(FATE_SLOTS).map(Number).sort((a, b) => a - b))
      if (!openSlots.has(s)) pool.push({ label: FATE_SLOTS[s], slot: s });
    for (const c of abil) if (c.lvl <= h.lvl && !openAbil.has(c.id)) pool.push(c);
    const label = `draw ${n} at level ${h.lvl}: ${h.name}`;
    if (h.seed === 2 || h.roll != null) {
      const r = pick(["roll", h.prev, int(h.roll), int(h.lvl), int(h.draw)], h.pool);
      const rollEntry = log.find((e) => e.kind === "ROLL" && e.h === h.prev);
      if (!rollEntry) bad(`${label}: no ROLL entry with hash ${String(h.prev).slice(0, 12)} in the log`);
      else if (!String(rollEntry.note).startsWith(int(h.roll) + " ")) bad(`${label}: roll ${h.roll} not what the ROLL entry says (${rollEntry.note})`);
      check(r, `roll ${h.roll}`);
    } else if (h.prev) {
      const r = pick([h.prev, int(h.st), int(h.lvl), int(h.draw)], h.pool);
      const fateEntry = log.find((e) => e.kind === "FATE" && String(e.note).includes(`draw ${h.draw}:`));
      if (fateEntry && bySeq[fateEntry.seq - 1]?.h !== h.prev) bad(`${label}: seed head is not the entry before the draw`);
      check(r, `server time ${int(h.st)}`);
    } else {
      console.log(`  --    ${label} (drawn before 0.10, no recorded seed, not replayable)`);
    }
    function check(r, source) {
      const c = pool[r.pick - 1];
      const same = c && (h.kind === "slot" ? c.slot === (h.slot ?? slotByName[h.name])
        : (h.card != null ? c.id === h.card : c.label === h.name || c.name === h.name));
      if (h.pool !== pool.length) bad(`${label}: pool had ${pool.length} cards, file says ${h.pool}`);
      else if (r.pick !== h.pick) bad(`${label}: replay picks ${r.pick}, file says ${h.pick}`);
      else if (!same) bad(`${label}: card ${r.pick} of the pool is ${c?.label}, but the file claims card ${h.card ?? h.slot ?? h.name}`);
      else good(`${label} (pick ${r.pick} of ${pool.length}, seeded by ${source})`);
    }
    if (h.kind === "slot") openSlots.add(h.slot ?? slotByName[h.name]);
    else { const a = cardOf(h); if (a) openAbil.add(a.id); else bad(`draw ${n}: ${h.name} is not a ${cls} card`); }
  });
  if (!hist.length) console.log("  --    no draws yet");

  // 4. record
  console.log("\nRecord");
  const count = (pred) => log.filter(pred).length;
  const viol = log.filter((e) => String(e.kind).startsWith("VIOLATION"));
  console.log(`  violations  ${viol.length}` + (viol.length ? ": " + viol.map((e) => `#${e.seq} ${e.kind.slice(10)}`).join(", ") : ""));
  const unacc = log.filter((e) => e.kind === "UNACCOUNTED").reduce((s, e) => s + (parseInt(e.note) || 0), 0);
  console.log(`  unaccounted ${Math.floor(unacc / 60)}m ${unacc % 60}s`);
  console.log(`  overrides   ${count((e) => ["MANUAL", "SETTOLL", "ROSTER+", "ROSTER-", "ROSTER_MANUAL", "ROSTER_CLEAR"].includes(e.kind))}`);
  console.log(`  sessions    ${count((e) => e.kind === "LOGIN")}, rolls ${count((e) => e.kind === "ROLL")}, witnesses heard ${count((e) => e.kind === "HEARD")}`);
  const ver = [...log].reverse().find((e) => e.kind === "VERSION");
  if (ver) console.log(`  addon       ${ver.note}`);

  console.log(problems ? `\n${problems} problem(s) found.\n` : "\nEverything checks out.\n");
  process.exit(problems ? 1 : 0);
}

main();
